FROM python:3.10-slim

WORKDIR /app

# instalar dependências
RUN pip install boto3 pandas kagglehub

# copiar o script
COPY ingest.py /app/ingest.py

# comando que roda automaticamente ao subir o container
CMD ["python", "ingest.py"]
